# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

IPS = [25, 28, 29, 37]
driver = webdriver.Chrome("/Users/departamentodeinformatica/Downloads/chromedriver")
arquivo = open("rotulos.txt", "w")
tempo = 5

def escrever(conteudo):
  arquivo.writelines(conteudo)

escrever("Relatorio impressoras Canon\n")

def rotulos():
  escrever("---------------------------------------\n")
  time.sleep(tempo)
  escrever("Serial: {}\n".format(driver.find_element(By.XPATH, "//div[@id=\'productInformation\']/table/tbody/tr[2]/td").text))
  time.sleep(tempo)
  driver.find_element(By.XPATH, "//div[@id=\'navStandard\']/ul/li/a/span").click()
  time.sleep(tempo)
  driver.find_element(By.XPATH, "//div[@id=\'navigation\']/ul[9]/li/a").click()
  time.sleep(tempo)
  escrever("{} - {}\n".format(driver.find_element(By.XPATH, "//div[@id=\'mainCounterInformationModule\']/div/div/table/tbody/tr/td").text, driver.find_element(By.XPATH, "//div[@id=\'mainCounterInformationModule\']/div/div/table/tbody/tr/td[2]").text))
  time.sleep(tempo)
  escrever("{} - {}\n".format(driver.find_element(By.XPATH, "//div[@id=\'mainCounterInformationModule\']/div/div/table/tbody/tr[2]/td").text, driver.find_element(By.XPATH, "//div[@id=\'mainCounterInformationModule\']/div/div/table/tbody/tr[2]/td[2]").text))
  time.sleep(tempo)
  escrever("{} - {}\n".format(driver.find_element(By.XPATH, "//div[@id=\'mainCounterInformationModule\']/div/div/table/tbody/tr[3]/td").text, driver.find_element(By.XPATH, "//div[@id=\'mainCounterInformationModule\']/div/div/table/tbody/tr[3]/td[2]").text))
  time.sleep(tempo)
  escrever("{} - {}\n".format(driver.find_element(By.XPATH, "//div[@id=\'mainCounterInformationModule\']/div/div/table/tbody/tr[4]/td").text, driver.find_element(By.XPATH, "//div[@id=\'mainCounterInformationModule\']/div/div/table/tbody/tr[4]/td[2]").text))
  time.sleep(tempo)

for ip in IPS:
  driver.get("http://192.168.112.{}:8000/".format(ip))
  time.sleep(tempo)
  if ip == 28:
    driver.find_element(By.XPATH, "//div[@id=\'loginContents\']/div[3]/fieldset/input[2]").click()
    rotulos()
    driver.find_element(By.XPATH, "//fieldset[@id=\'authTools\']/a/span").click()
  else:
    rotulos()

escrever("---------------------------------------")
driver.close()